export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";